# Site settings
title: Dover Framework
email: efpiva@gmail.com
description: "Dover Framework. A Development Framework for SAP Business One, working with SAP Business One Studio on SQL and HANA."
baseurl: ""
url: "http://efpiva.github.io"
# twitter_username: jekyllrb
github_username:  efpiva

# Build settings
markdown: kramdown
permalink: pretty
